export const homeObjOne = {
  lightBg: false,
  primary: true,
  lightTopLine: true,
  lightText: true,
  lightTextDesc: true,
  buttonLabel: "Get Started",
  description: "We help business owners increase their revenue. Our team of unique specialist can help you achieve your business goals.",
  headline: "Lead Generation Specialist for Online Business",
  topLine: "Marketing Agency",
  imgStart: "",
  img: require("../../images/svg-1.svg").default,
  alt: "Image",
  start: "",
};

export const homeObjTwo = {
  primary: true,
  lightBg: true,
  lightTopLine: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Instant Setup",
  headline: "Extremely quick onboarding process",
  description: "Once you've joined, our team of specialist will reach out to you and get you set up in minutes.",
  buttonLabel: "Learn More",
  imgStart: "",
  img: require("../../images/svg-2.svg").default,
  alt: "Vault",
  start: "",
};

export const homeObjThree = {
  primary: false,
  lightBg: true,
  lightTopLine: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Sarah Jeni",
  headline: "Ultra helped me increase my revenue by over 3X in less than 3 months!",
  description: "Their team is wonderful! I can't believe I didn't start working with them earlier.",
  buttonLabel: "View Case Study",
  imgStart: "start",
  img: require("../../images/profile.jpg"),
  alt: "Vault",
  start: "true",
};

export const homeObjFour = {
  primary: true,
  lightBg: false,
  lightTopLine: true,
  lightText: true,
  lightTextDesc: true,
  topLine: "Secure Database",
  headline: "All your data is stored on our secure server",
  description: "You will never have to worry about your information getting leaked. Our team of security experts will ensure your records are kept safe.",
  buttonLabel: "Sign Up Now",
  imgStart: "start",
  img: require("../../images/svg-3.svg").default,
  alt: "Vault",
  start: "true",
};
